#!/bin/bash
# Author: Nikolay <nikolatsio> Nikolov
# E-mail: niki@tintirimintiri.org
# Web: https://tintirimintiri.org

echo -n "Please enter password lenght, followed by [ENTER]: "
read LONG
if [ $LONG -ne 0 -o $LONG -eq 0 2>/dev/null ]
then
	#if [ -z $LONG ]; then
	#echo "Please enter at least 1 character!"
	if [ "$LONG" -le "0" ]; then
		echo "The password must be greater than 0!"
	else
	echo -n "Your password is: "
	cat /dev/urandom | tr -dc A-Za-z0-9 | head -c $LONG && echo
	fi

else 
	echo "Supplied input ($LONG) is not an number."	
fi
